[tool.poetry]
name = "patchdiff"
version = "0.3.1"
description = "MIT"
authors = ["Korijn van Golen <korijn@gmail.com>"]
homepage = "https://github.com/Korijn/patchdiff"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
flake8 = "*"
black = "*"
flake8-black = "*"
flake8-import-order = "*"
flake8-print = "*"
pytest = "*"
twine = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
