[project]
name = "patchdiff"
version = "0.3.4"
description = "MIT"
authors = [
    { name = "Korijn van Golen", email = "korijn@gmail.com" },
    { name = "Berend Klein Haneveld", email = "berendkleinhaneveld@gmail.com" },
]
requires-python = ">=3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/fork-tongue/patchdiff"

[dependency-groups]
dev = [
    "flake8",
    "black",
    "flake8-black",
    "flake8-import-order",
    "flake8-print",
    "pytest",
    "pytest-cov",
    "pytest-watch",
    "twine",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
